name: xai_dashboard_env
channels:
   - conda-forge
dependencies:
   - python=3.9
   - numpy=1.24
   - pandas=1.5
   - scikit-learn=1.2
   - streamlit=1.14
   - shap=0.41
   - lime=0.2.0.1
   - pytest=7.2
   - pytest-cov=4.0.0
   - joblib=1.2
   - pip:
        - ...
